name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Archive build files
        run: tar -czf dist.tar.gz dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Check downloaded files
        run: ls -al # 다운로드된 파일 확인

      - name: Extract artifact
        run: tar -xzf ${{ github.workspace }}/dist.tar.gz -C ${{ github.workspace }}/

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf ./portfolio/dist
            mkdir -p ./portfolio
            scp ${{ github.workspace }}/portfolio/dist.tar.gz ./portfolio/
            tar -xzf ./portfolio/dist.tar.gz -C ./portfolio/
