name: Deploy Retro Branch

on:
  push:
    branches:
      - retro
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf retro
            git clone https://github.com/jbj338033/portfolio.git -b retro retro
            cd retro
            npm install
            npm run build
            cd ..
